export interface Ingredients {
  id: string;
  name: string;
  caloriesPerUnit: number;
  measurementUnit: string;
}

export const sampleIngredients: Ingredients[] = [
  { id: '1', name: 'Ức gà', caloriesPerUnit: 1.65, measurementUnit: 'g' },
  { id: '2', name: 'Thịt bò thăn', caloriesPerUnit: 2.50, measurementUnit: 'g' },
  { id: '3', name: 'Thịt lợn nạc', caloriesPerUnit: 1.43, measurementUnit: 'g' },
  { id: '4', name: 'Cá hồi', caloriesPerUnit: 2.08, measurementUnit: 'g' },
  { id: '5', name: 'Cá thu', caloriesPerUnit: 2.05, measurementUnit: 'g' },
  { id: '6', name: 'Tôm sú', caloriesPerUnit: 0.99, measurementUnit: 'g' },
  { id: '7', name: 'Trứng gà', caloriesPerUnit: 1.55, measurementUnit: 'g' },
  { id: '8', name: 'Gạo trắng', caloriesPerUnit: 1.30, measurementUnit: 'g' },
  { id: '9', name: 'Gạo lứt', caloriesPerUnit: 1.23, measurementUnit: 'g' },
  { id: '10', name: 'Mì ống', caloriesPerUnit: 1.31, measurementUnit: 'g' },
  { id: '11', name: 'Bún gạo', caloriesPerUnit: 1.10, measurementUnit: 'g' },
  { id: '12', name: 'Khoai tây', caloriesPerUnit: 0.77, measurementUnit: 'g' },
  { id: '13', name: 'Khoai lang', caloriesPerUnit: 0.86, measurementUnit: 'g' },
  { id: '14', name: 'Cà rốt', caloriesPerUnit: 0.41, measurementUnit: 'g' },
  { id: '15', name: 'Bắp cải', caloriesPerUnit: 0.25, measurementUnit: 'g' },
  { id: '16', name: 'Cải bó xôi', caloriesPerUnit: 0.23, measurementUnit: 'g' },
  { id: '17', name: 'Rau muống', caloriesPerUnit: 0.20, measurementUnit: 'g' },
  { id: '18', name: 'Cà chua', caloriesPerUnit: 0.18, measurementUnit: 'g' },
  { id: '19', name: 'Dưa leo', caloriesPerUnit: 0.16, measurementUnit: 'g' },
  { id: '20', name: 'Hành tây', caloriesPerUnit: 0.40, measurementUnit: 'g' },
  { id: '21', name: 'Tỏi', caloriesPerUnit: 1.49, measurementUnit: 'g' },
  { id: '22', name: 'Gừng', caloriesPerUnit: 0.80, measurementUnit: 'g' },
  { id: '23', name: 'Nước mắm', caloriesPerUnit: 0.35, measurementUnit: 'ml' },
  { id: '24', name: 'Dầu ô liu', caloriesPerUnit: 8.84, measurementUnit: 'ml' },
  { id: '25', name: 'Dầu ăn thực vật', caloriesPerUnit: 8.84, measurementUnit: 'ml' },
  { id: '26', name: 'Đường trắng', caloriesPerUnit: 3.87, measurementUnit: 'g' },
  { id: '27', name: 'Muối', caloriesPerUnit: 0, measurementUnit: 'g' },
  { id: '28', name: 'Tiêu đen', caloriesPerUnit: 2.51, measurementUnit: 'g' },
  { id: '29', name: 'Sữa tươi không đường', caloriesPerUnit: 0.42, measurementUnit: 'ml' },
  { id: '30', name: 'Sữa đặc', caloriesPerUnit: 3.21, measurementUnit: 'g' },
  { id: '31', name: 'Phô mai cheddar', caloriesPerUnit: 4.03, measurementUnit: 'g' },
  { id: '32', name: 'Bơ lạt', caloriesPerUnit: 7.17, measurementUnit: 'g' },
  { id: '33', name: 'Chuối', caloriesPerUnit: 0.89, measurementUnit: 'g' },
  { id: '34', name: 'Táo', caloriesPerUnit: 0.52, measurementUnit: 'g' },
  { id: '35', name: 'Xoài', caloriesPerUnit: 0.60, measurementUnit: 'g' },
  { id: '36', name: 'Dứa', caloriesPerUnit: 0.50, measurementUnit: 'g' },
  { id: '37', name: 'Đậu phộng', caloriesPerUnit: 5.67, measurementUnit: 'g' },
  { id: '38', name: 'Hạt điều', caloriesPerUnit: 5.53, measurementUnit: 'g' },
  { id: '39', name: 'Đậu đỏ', caloriesPerUnit: 3.37, measurementUnit: 'g' },
  { id: '40', name: 'Đậu xanh', caloriesPerUnit: 3.47, measurementUnit: 'g' },
  { id: '41', name: 'Nấm hương', caloriesPerUnit: 0.34, measurementUnit: 'g' },
  { id: '42', name: 'Nấm rơm', caloriesPerUnit: 0.22, measurementUnit: 'g' },
  { id: '43', name: 'Măng tây', caloriesPerUnit: 0.20, measurementUnit: 'g' },
  { id: '44', name: 'Bí đỏ', caloriesPerUnit: 0.26, measurementUnit: 'g' },
  { id: '45', name: 'Bí xanh', caloriesPerUnit: 0.17, measurementUnit: 'g' },
  { id: '46', name: 'Ớt chuông', caloriesPerUnit: 0.27, measurementUnit: 'g' },
  { id: '47', name: 'Hành lá', caloriesPerUnit: 0.32, measurementUnit: 'g' },
  { id: '48', name: 'Rau mùi', caloriesPerUnit: 0.23, measurementUnit: 'g' },
  { id: '49', name: 'Thì là', caloriesPerUnit: 0.30, measurementUnit: 'g' },
  { id: '50', name: 'Mật ong', caloriesPerUnit: 3.04, measurementUnit: 'g' },
  { id: '51', name: 'Nước cốt dừa', caloriesPerUnit: 2.30, measurementUnit: 'ml' },
  { id: '52', name: 'Bột mì', caloriesPerUnit: 3.64, measurementUnit: 'g' },
  { id: '53', name: 'Bột năng', caloriesPerUnit: 3.59, measurementUnit: 'g' },
  { id: '54', name: 'Thịt ba chỉ', caloriesPerUnit: 5.41, measurementUnit: 'g' },
  { id: '55', name: 'Cá basa', caloriesPerUnit: 1.18, measurementUnit: 'g' },
];